baseurl = "http://jack2code.com/"
title = "Jack Leung"
languageCode = "zh-CN"
disqusShortname = "jack2code"
copyright = "Copyright (c) 2010 - 2017, Jack Leung; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Jack Leung"

[indexes]
    tag = "tags"
    topic = "topics"

